steps:
  # 1. Build Flutter APK
  - name: 'ghcr.io/cirruslabs/flutter:stable'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Check Flutter/Dart versions
        flutter --version
        dart --version

        # (Optional) Print working dir and contents
        pwd
        ls -la

        # Clean and get dependencies
        flutter clean
        flutter pub get

        # Ensure android/ exists
        if [ ! -d "android" ]; then
          echo "Android directory not found, regenerating..."
          flutter create --platforms=android .
        fi

        ls -la android/
        ls -la android/app/src/main/

        # Clean Android build
        cd android
        ./gradlew clean
        cd ..

        # Build APK for ARM64
        flutter build apk --release --target-platform android-arm64

  # 2. Upload APK to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
      'cp',
      'build/app/outputs/flutter-apk/app-release.apk',
      'gs://idea-forge-459803_cloudbuild/ideaforge-builds/${SHORT_SHA}_app-release.apk'
    ]

artifacts:
  objects:
    location: 'gs://idea-forge-459803_cloudbuild/ideaforge-builds/'
    paths: ['build/app/outputs/flutter-apk/app-release.apk']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
