steps:
  # Build Flutter APK
  - name: 'cirrusci/flutter:stable'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd app
        flutter pub get
        flutter build apk --release

  # Upload APK to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
      'cp',
      'app/build/app/outputs/flutter-apk/app-release.apk',
      'gs://ideaforge-apks-aaron/ideaforge-builds/${SHORT_SHA}_app-release.apk'
    ]

  # Create Pull Request from generated-app to main
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install GitHub CLI
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

        # Configure GitHub CLI
        echo "$_GITHUB_TOKEN" | gh auth login --with-token

        # Create PR
        gh pr create \
          --base main \
          --head generated-app \
          --title "Generated App Update - Build ${SHORT_SHA}" \
          --body "This PR contains the latest generated app changes and APK build. Build ID: ${SHORT_SHA}"
    secretEnv: ['_GITHUB_TOKEN']

artifacts:
  objects:
    location: 'gs://ideaforge-apks-aaron/ideaforge-builds/'
    paths: ['app/build/app/outputs/flutter-apk/app-release.apk']

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: '_GITHUB_TOKEN'
