steps:
  # Debug: List workspace contents
  - name: 'ubuntu'
    args: ['ls', '-la', '/workspace']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ideaforge-backend', '.']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ideaforge-backend']

images:
  - 'gcr.io/$PROJECT_ID/ideaforge-backend'

timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY 